<center>

# Python for Quantum Mechanics: 
# Week 4 Exercises

</center>

In [1]:
import numpy as np
import numpy.random as rnd

<center>

## Exercise 1: Triggy Problem

</center>

Create arrays, of $sin(x)$ and $cos(x)$, with 100 elements that ranges between $-\pi$ and $\pi$. Round the arrays to three decimal places.

In [36]:
step = 100

arr1 = np.round(np.sin(np.linspace(-np.pi,np.pi,step)),3)
arr2 = np.round(np.cos(np.linspace(-np.pi,np.pi,step)),3)

print('arr1 = ',arr1)

arr1 =  [-0.    -0.063 -0.127 -0.189 -0.251 -0.312 -0.372 -0.43  -0.486 -0.541
 -0.593 -0.643 -0.69  -0.735 -0.776 -0.815 -0.85  -0.881 -0.91  -0.934
 -0.955 -0.972 -0.985 -0.994 -0.999 -1.    -0.997 -0.99  -0.979 -0.964
 -0.945 -0.922 -0.896 -0.866 -0.833 -0.796 -0.756 -0.713 -0.667 -0.618
 -0.567 -0.514 -0.458 -0.401 -0.342 -0.282 -0.22  -0.158 -0.095 -0.032
  0.032  0.095  0.158  0.22   0.282  0.342  0.401  0.458  0.514  0.567
  0.618  0.667  0.713  0.756  0.796  0.833  0.866  0.896  0.922  0.945
  0.964  0.979  0.99   0.997  1.     0.999  0.994  0.985  0.972  0.955
  0.934  0.91   0.881  0.85   0.815  0.776  0.735  0.69   0.643  0.593
  0.541  0.486  0.43   0.372  0.312  0.251  0.189  0.127  0.063  0.   ]


Find the mean and variance of the above arrays, round your answer to one decimal place.

In [37]:
print('mean1 = ',np.round(np.mean(arr1),1))
print('var1 = ',np.round(np.var(arr1),1))

print('mean2 = ',np.round(np.mean(arr2),1))
print('var2 = ',np.round(np.var(arr2),1))

mean1 =  -0.0
var1 =  0.5
mean2 =  -0.0
var2 =  0.5


Now generate a new array, that is the squared sum of the two arrays found above. Round the array to two decimal places.

In [38]:
arr = np.round(arr1**2 + arr2**2,2)
print('arr = ',arr)

arr =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


Now find the sum of the array, print the shape of the array aswell.

In [39]:
print('sum = ',sum(arr))
print('shape = ',arr.shape)

sum =  100.0
shape =  (100,)


<center>

## Exercise 2: Quantum State Measurements

</center>

The probability of finding quantum objects in certain states is given by the square of the coefficient to those states, when written in a normailised form. For example:

$$ |{\psi}> = \frac{1}{\sqrt{2}}|{0}> + \frac{1}{\sqrt{2}}|{1}>$$

The probability that the quantum object being in the state $|{0}>$ is $(\frac{1}{\sqrt{2}})^2 = 0.5$. Similary the probability of being in the state $|{1}>$ is also $(\frac{1}{\sqrt{2}})^2 = 0.5$. Notice that the sum of these probabilities is $0.5+0.5=1$, which, not only makes probabilistic sense(there is a $100\%$ chance of being in some state), but also tells us the states are correctly normalised. 

The file "normalised_quibits.txt" contains rows of normalised states of quantum-type objects. We can interpret the first column as the coefficients of $|{0}>$ and the second column as $|{1}>$.

Read in the file and calculate the probability that the 4th quibit is in state $|{0}>$.

In [57]:
quibits = np.loadtxt("normalised_quibits.txt", delimiter=' ')

print(quibits[3,0]**2)

0.004393479829360381


Now calculate the probability that the entire set of quibits are found in the following states. Also find the probability as a percentage.

$$ |{1}> , |{1}>, |{1}>, |{1}>, |{0}>, |{1}>, |{0}>, |{0}>, |{1}>, |{0}>$$

In [58]:
q = np.arange(10)
s = [1,1,1,1,0,1,0,0,1,0]

print('entire_state = ',quibits[q,s], '\n')

print('probability = ', np.prod(quibits[q,s]**2))

print('percentage probability = ', np.prod(quibits[q,s]**2)*100,'%')

entire_state =  [0.73593101 0.99984837 0.9996358  0.99780084 0.99986066 0.99923493
 0.99995767 0.54128523 0.99996849 0.6054546 ] 

probability =  0.057740347227321895
percentage probability =  5.774034722732189 %


<center>

## Exercise 3: Multiple Quibit Measurements

</center>

Continuining from the last exercise. Given that 

$$ |{1}> , |{1}>, |{1}>, |{1}>, |{0}>, |{1}>, |{0}>, |{0}>, |{1}>, |{0}>$$

is just one possible state these ten quibits can characterise. How many possible states can these ten quantum objects(quibits) characterise?

In [214]:
nq = 10
n=2**nq

print(n)

1024


Create an array/matrix of shape (number_of_possible states,number_of_qubits), where each row is a unique state the quibits can have. 

(Hint: use binary operations and loops)

In [225]:
states = np.zeros((n,nq),dtype=int)

for i in range(n):
    bina = bin(i)[2:]
    bina = '0'*(nq-len(bina))+bina
    states[i,0:] = np.array(bina,dtype = 'c')

print(states[0:10],'\n')
print(states[-10:])

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 1]] 

[[1 1 1 1 1 1 0 1 1 0]
 [1 1 1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 0 0 0]
 [1 1 1 1 1 1 1 0 0 1]
 [1 1 1 1 1 1 1 0 1 0]
 [1 1 1 1 1 1 1 0 1 1]
 [1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 0 1]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1]]


Now, create a random,normalised set of states for ten quibits, with shape(nq,2),similar to the "normalised_quibits.txt" file.

In [227]:
quibits = rnd.random((nq,2))

#Normalise
quibits[0:,0], quibits[0:,1] = quibits[0:,0]/np.sqrt(quibits[0:,0]**2+quibits[0:,1]**2), quibits[0:,1]/np.sqrt(quibits[0:,0]**2+quibits[0:,1]**2)

print(quibits, '\n')

[[0.4668577  0.88433245]
 [0.38192358 0.92419391]
 [0.45272942 0.89164795]
 [0.5811217  0.81381667]
 [0.88807202 0.45970434]
 [0.80184189 0.59753626]
 [0.68638735 0.72723614]
 [0.17663078 0.98427718]
 [0.80133658 0.59821375]
 [0.19465515 0.98087174]] 



Using the two arrays created above, create an array that contains the probabilities of each possible global state being measured, given the qubits are in this state.

In [228]:
q = np.arange(nq)
prob = np.prod(np.array(quibits[q,states]**2),axis=1)
print(prob)

[3.99062113e-07 1.01328860e-05 2.22394143e-07 ... 8.40084904e-03
 1.84379812e-04 4.68172639e-03]


Find the sum of this array. Round the answer to two decimal places.

In [230]:
print(np.round(sum(prob),2))

1.0


## Exercise 4: Matrix Eigenvectors & Eigenvalues

Create a random matrix with shape (3,3).

In [280]:
A = 100*rnd.random((3,3))
print(A)

[[38.53674284 16.19648851 39.56281766]
 [53.80376283 80.81393217 98.15918545]
 [97.37831509 49.73487913 75.0459709 ]]


Find the eigenvalues and eigenvectors of this array

In [281]:
eigval, E = np.linalg.eig(A) 
print(np.round(eigval,3),'\n')
print(np.round(E,3))

[178.36  -13.416  29.452] 

[[ 0.259  0.393  0.322]
 [ 0.752  0.546 -0.9  ]
 [ 0.606 -0.74   0.295]]


Using the matrix of eigenvectors, diagonalise the original matrix. Round the answer to 3 decimal places.

In [282]:
D = np.matmul(np.linalg.inv(E),np.matmul(A,E))

print(np.round(D,3))

[[178.36    0.     -0.   ]
 [  0.    -13.416   0.   ]
 [  0.     -0.     29.452]]


The diagonal matrix $D$ was found using the formula

$$ D = E^{-1}AE $$

Where $A$ is the original matrix, and $E$ is the matrix of eigenvectors. Let's raise both sides of this formula to the power of an integer $n$.

$$ D^{n} = (E^{-1}AE)^n $$
$$ D^{n} = (E^{-1}AE)(E^{-1}AE)(E^{-1}AE)...(E^{-1}AE) $$

Notice that $E^{-1}E=identity$,

$$\implies  D^{n} = E^{-1}A^nE $$

And rearranging:

$$ ED^{n}E^{-1} = A^n $$

Because $D^{n}$ is very easy to calculate, we just raise the diagonal elements to the power of $n$, we have greatly simplified finding the power of a non-diagonal matrix $A$. 

Use this formula to calculate $A^{30}$

In [283]:
power = 5

D = D**power

Apow = np.matmul(E,np.matmul(D,np.linalg.inv(E)))

print(np.round(Apow,3))

[[3.28516158e+10 2.30098567e+10 3.44442951e+10]
 [9.55293612e+10 6.69699151e+10 1.00204262e+11]
 [7.69637824e+10 5.39212928e+10 8.07047857e+10]]


Alternatively, you could simply convert $A$ to a matrix with $np.matrix()$ and use $**$, do this and compare your results.

In [287]:
print(np.round(np.matrix(A)**power,3), '\n')

print(np.round(np.matrix(A)**power,3)==np.round(Apow,3))

[[3.28516158e+10 2.30098567e+10 3.44442951e+10]
 [9.55293612e+10 6.69699151e+10 1.00204262e+11]
 [7.69637824e+10 5.39212928e+10 8.07047857e+10]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
